/* Generated by tools/gen_encoding_tables.py from the codecs of Python 3.12.9
 * (2026-09-29) — do not edit by hand; see the generator for the rules.
 *
 * The code-page tables behind engine/legacy_encoding (ENC-3). 0xFFFF marks a
 * byte or byte pair the code page does not define. */
#pragma once

#include <cstddef>
#include <cstdint>

namespace parqit {
namespace enctab {

constexpr size_t kSingleCount = 49;
extern const uint16_t kSingleTable[kSingleCount][256];
extern const bool kSingleAsciiIdentity[kSingleCount];
extern const char *const kSingleName[kSingleCount];

/* Microsoft double-byte code pages: pairs indexed
 * (lead - lead_lo) * span + (trail - trail_lo); Single = bytes 0x80-0xFF */
constexpr uint8_t kCp932LeadLo = 0x81, kCp932LeadHi = 0xFC, kCp932TrailLo = 0x40, kCp932TrailHi = 0xFC;
extern const uint16_t kCp932Pairs[23436];
extern const uint16_t kCp932Single[128];
constexpr uint8_t kCp936LeadLo = 0x81, kCp936LeadHi = 0xFE, kCp936TrailLo = 0x40, kCp936TrailHi = 0xFE;
extern const uint16_t kCp936Pairs[24066];
extern const uint16_t kCp936Single[128];
constexpr uint8_t kCp949LeadLo = 0x81, kCp949LeadHi = 0xFE, kCp949TrailLo = 0x41, kCp949TrailHi = 0xFE;
extern const uint16_t kCp949Pairs[23940];
extern const uint16_t kCp949Single[128];
constexpr uint8_t kCp950LeadLo = 0x81, kCp950LeadHi = 0xFE, kCp950TrailLo = 0x40, kCp950TrailHi = 0xFE;
extern const uint16_t kCp950Pairs[24066];
extern const uint16_t kCp950Single[128];

/* EUC-JP: JIS X 0208 and JIS X 0212, row-major over 0xA1-0xFE x 0xA1-0xFE */
extern const uint16_t kJis0208[94 * 94];
extern const uint16_t kJis0212[94 * 94];

/* GB18030: the two-byte table is 936's with these changes (index into the
 * 0x81-0xFE x 0x40-0xFE rectangle), and the four-byte BMP pointers map by
 * runs: the last range at or below a pointer gives cp + (pointer - start) */
struct PairDiff {
    uint32_t index;
    uint16_t cp;
};
constexpr size_t kGb18030DiffCount = 82;
extern const PairDiff kGb18030Diff[kGb18030DiffCount];
struct Range4 {
    uint32_t pointer;
    uint32_t cp;
};
constexpr size_t kGb18030RangeCount = 208;
extern const Range4 kGb18030Ranges[kGb18030RangeCount];

/* every accepted name, lower-case without - _ . and blanks, sorted */
struct Alias {
    const char *key;
    const char *canonical;
};
constexpr size_t kAliasCount = 232;
extern const Alias kAlias[kAliasCount];

} // namespace enctab
} // namespace parqit
