* ============================================================================
* parqit tour — full functional test + exploration suite over artificial data
*
* Usage:
*   . do parqit_tour.do                       (parqit already installed/adopath'd)
*   . do parqit_tour.do <repo_root> <plugin>  (development tree)
*
* Small synthetic datasets are generated by examples/make_data.py (pyarrow);
* because they are small, a "native twin" is loaded into memory first and
* native Stata computes the oracle for every lazy result we check.
* Every section prints visible exploration output AND asserts correctness.
* ============================================================================
clear all
set more off
set linesize 100
args repo plugin

if (`"`repo'"' != "") {
    adopath ++ `"`repo'/src/ado/p"'
    global PARQIT_PLUGIN_PATH `"`plugin'"'
    local mkdata `"`repo'/examples/make_data.py"'
}
else {
    * installed mode: make_data.py is expected next to this do-file
    local mkdata "make_data.py"
    * if parqit is not on the adopath yet, find the repo-local install tree
    * (this file lives in <repo>/examples, the tree in <repo>/ado/plus/p)
    capture which parqit
    if (_rc) {
        foreach try in "../ado/plus/p" "ado/plus/p" {
            capture confirm file "`try'/parqit.ado"
            if (_rc == 0) {
                adopath ++ "`try'"
                continue, break
            }
        }
    }
    which parqit
}

di as txt _n "{hline 78}"
di as txt "parqit tour — section 0: setup and artificial data"
di as txt "{hline 78}"

parqit version
parqit selftest
assert "`r(selftest)'" == "ok"

capture confirm file workers.parquet
if (_rc) {
    shell python3 "`mkdata'" .
}
confirm file workers.parquet
confirm file firms.parquet
confirm file patents.parquet
confirm file wide_income.parquet
confirm file messy.parquet

* ----------------------------------------------------------------------------
di as txt _n "{hline 78}"
di as txt "section 1: plain I/O — read whole file, describe, metadata round-trip"
di as txt "{hline 78}"

parqit describe workers.parquet
assert r(n_rows) == 600 & r(n_cols) == 13
parqit glimpse workers.parquet
assert r(n_rows) == 600 & r(n_cols) == 13
parqit path workers.parquet
assert r(exists) == 1 & `"`r(path)'"' != ""

parqit use workers.parquet, clear
assert _N == 600 & c(k) == 13
assert c(changed) == 0 & `"`c(filename)'"' == ""

* decorate and write back: labels/notes must survive a parqit round-trip
label variable wage "hourly wage (EUR)"
label define edlbl 1 "basic" 2 "secondary" 3 "tertiary" 4 "phd"
label values education edlbl
note: tour fixture rebuilt by parqit_tour.do
parqit save tour_workers.parquet, replace
parqit use tour_workers.parquet, clear
assert `"`: variable label wage'"' == "hourly wage (EUR)"
assert `"`: label edlbl 3'"' == "tertiary"
assert `"`: char _dta[note1]'"' != ""

* native twin + oracles for everything below
tempfile twin
qui save `"`twin'"'
qui count if missing(wage)
local o_miss = r(N)
qui count if age >= 25 & age <= 54 & !missing(wage)
local o_prime = r(N)
qui summ wage, detail
local o_p50 = r(p50)
local o_kurt = r(kurtosis)
qui correlate wage tenure
local o_rho = r(rho)
qui levelsof region, local(o_regions)
qui duplicates report id
local o_uniq = r(unique_value)
qui count if gender == "F" & education == 3
local o_cell = r(N)
egen byte o_mm = rowmiss(id year wage age gender education region sector ///
    firm_id hours tenure hire_date note)
qui count if o_mm == 0
local o_complete = r(N)
drop o_mm
bysort firm_id: gen long o_fsize = _N
qui summ o_fsize, meanonly
local o_maxfirm = r(max)
drop o_fsize

* ----------------------------------------------------------------------------
di as txt _n "{hline 78}"
di as txt "section 2: named lazy views"
di as txt "{hline 78}"

clear
parqit use using tour_workers.parquet, name(w)
assert "`r(view)'" == "w" & r(k) == 13
parqit use using firms.parquet, name(f)
parqit use using patents.parquet, name(p)
parqit views
assert r(n_views) == 3
parqit view w
parqit describe
assert r(n_cols) == 13

* ----------------------------------------------------------------------------
di as txt _n "{hline 78}"
di as txt "section 3: exploration without materialising (memory stays empty)"
di as txt "{hline 78}"

assert _N == 0 & c(k) == 0     // nothing in memory throughout this section

parqit ds
assert `: word count `r(varlist)'' == 13
parqit lookfor wage hire
assert "`r(varlist)'" == "wage hire_date"

parqit codebook id wage gender region hire_date

parqit count
assert r(N) == 600
parqit count if missing(wage)
assert r(N) == `o_miss'
parqit count if age >= 25 & age <= 54 & !missing(wage)
assert r(N) == `o_prime'

parqit list id year wage gender in 1/8
parqit list id wage if missing(wage) in 1/40
parqit list id year wage if wage > 120 & !missing(wage)

parqit misstable
assert r(N) == 600
assert r(n_complete) == `o_complete'
parqit misstable patterns wage note age

parqit summarize wage age hours
parqit summarize wage, detail
assert reldif(r(p50), `o_p50') < 1e-12
assert reldif(r(kurtosis), `o_kurt') < 1e-10

parqit tabulate gender
parqit tabulate education
parqit tabulate region sector
parqit tabulate gender education, row col
qui parqit count if gender == "F" & education == 3
assert r(N) == `o_cell'

parqit tabstat wage age tenure, statistics(n mean sd p25 p50 p75 max)
parqit tabstat wage, statistics(n mean sd) by(region)

parqit correlate wage age tenure
parqit pwcorr wage age tenure, obs sig
qui parqit correlate wage tenure
assert reldif(r(rho), `o_rho') < 1e-12

parqit distinct id firm_id region
parqit distinct id year, joint
assert r(ndistinct) == 600

parqit levelsof region
assert `"`r(levels)'"' == `"`o_regions'"'
parqit levelsof education
assert "`r(levels)'" == "1 2 3 4"

parqit duplicates report id
assert r(unique_value) == `o_uniq'
parqit duplicates report id year
assert r(surplus) == 0
parqit duplicates list id, limit(6)

parqit histogram wage, bins(25) nodraw
assert r(bins) == 25
assert r(N) == 600 - `o_miss'
capture noisily parqit histogram wage, bins(25)
capture graph export parqit_tour_hist.png, replace
if (_rc == 0) di as txt "(histogram exported to parqit_tour_hist.png)"

assert _N == 0 & c(k) == 0     // still nothing materialised

* ----------------------------------------------------------------------------
di as txt _n "{hline 78}"
di as txt "section 4: single-table verbs (lazy pipeline) vs the native twin"
di as txt "{hline 78}"

parqit keep if !missing(wage) & inrange(age, 20, 60)
parqit gen double lwage = ln(wage)
parqit gen byte senior = cond(age >= 45, 1, 0)
parqit egen double fw = total(wage), by(firm_id year)
parqit replace note = "checked" if note == ""
parqit rename hours weekly_hours
parqit order id year wage lwage
parqit sort firm_id year id
parqit show
parqit explain
parqit count
local n_pipe = r(N)

* the same pipeline natively
preserve
use `"`twin'"', clear
keep if !missing(wage) & inrange(age, 20, 60)
qui count
assert r(N) == `n_pipe'
gen double lwage = ln(wage)
qui summ lwage
local o_lwsum = r(sum)
restore

qui parqit tabstat lwage, statistics(sum)
parqit summarize lwage
assert reldif(r(N) * r(mean), `o_lwsum') < 1e-9

* slicing, sampling, dedup, contract
parqit keep in 1/100
parqit count
assert r(N) == 100
parqit sample 25, count seed(42)
parqit count
assert r(N) == 25
parqit close

parqit use using tour_workers.parquet, name(w)
parqit sort id year
parqit duplicates drop id, force
parqit count
assert r(N) == 200
parqit close

parqit use using tour_workers.parquet, name(w)
parqit contract region sector
parqit collect, clear
assert c(k) == 3
qui summ _freq
assert r(sum) == 600
parqit close _all

* drop (varlist and if) and gsort vs the native twin, missings included
parqit use using tour_workers.parquet, name(w)
parqit drop note hire_date
parqit drop if education == 1
parqit gsort -wage id year
parqit collect, clear
tempfile got
qui save `"`got'"'
use `"`twin'"', clear
drop note hire_date
drop if education == 1
gsort -wage id year
cf _all using `"`got'"'
parqit close _all

* ----------------------------------------------------------------------------
di as txt _n "{hline 78}"
di as txt "section 5: collapse vs native collapse (cell-exact)"
di as txt "{hline 78}"

clear
parqit use using tour_workers.parquet, name(w)
parqit keep if !missing(wage)
parqit collapse (mean) mwage = wage (p50) medwage = wage (count) n = wage, by(region)
parqit sort region
parqit collect, clear
tempfile parqitcol
qui save `"`parqitcol'"'

use `"`twin'"', clear
keep if !missing(wage)
collapse (mean) mwage_o = wage (p50) medwage_o = wage (count) n_o = wage, by(region)
sort region
qui merge 1:1 region using `"`parqitcol'"', assert(match) nogenerate
gen double d1 = reldif(mwage, mwage_o)
gen double d2 = reldif(medwage, medwage_o)
qui summ d1
assert r(max) < 1e-12
qui summ d2
assert r(max) < 1e-12
assert n == n_o
di as txt "collapse: every cell equals native Stata"

* ----------------------------------------------------------------------------
di as txt _n "{hline 78}"
di as txt "section 6: two-table verbs — merge / joinby / append / view:"
di as txt "{hline 78}"

* .dta twins of the using files, for native oracles
clear
parqit use firms.parquet, clear
tempfile firmsdta
qui save `"`firmsdta'"'
clear
parqit use patents.parquet, clear
tempfile patsdta
qui save `"`patsdta'"'

use `"`twin'"', clear
qui merge m:1 firm_id using `"`firmsdta'"', keep(match) nogenerate
qui count
local o_matched = r(N)
qui summ tfp
local o_tfpsum = r(sum)

clear
parqit use using tour_workers.parquet, name(w)
parqit merge m:1 firm_id using firms.parquet, keep(match) keepusing(tfp industry) nogenerate
parqit count
assert r(N) == `o_matched'
qui parqit tabstat tfp, statistics(sum)
parqit summarize tfp
assert reldif(r(N) * r(mean), `o_tfpsum') < 1e-9

* joinby patents (cartesian within firm)
use `"`twin'"', clear
qui joinby firm_id using `"`patsdta'"'
local o_join = _N

clear
parqit use using tour_workers.parquet, name(w)
parqit joinby firm_id using patents.parquet
parqit count
assert r(N) == `o_join'
parqit close _all

* append: split the panel by year through views, then reassemble
clear
parqit use using tour_workers.parquet, name(early)
parqit keep if year <= 2020
parqit use using tour_workers.parquet, name(late)
parqit keep if year == 2021
parqit view early
parqit append using view:late, generate(part)
parqit count
assert r(N) == 600
parqit collect, clear
qui count if part == 1
assert r(N) == 200
parqit close _all

* merge across two filtered views, nothing materialised
clear
parqit use using tour_workers.parquet, name(w)
parqit keep if year == 2021
parqit use using tour_workers.parquet, name(stats)
parqit collapse (mean) avg_wage = wage, by(firm_id)
parqit view w
parqit merge m:1 firm_id using view:stats, keep(match)
parqit count
assert r(N) == 200
parqit close _all

* ----------------------------------------------------------------------------
di as txt _n "{hline 78}"
di as txt "section 7: reshape long and wide vs native"
di as txt "{hline 78}"

clear
parqit use wide_income.parquet, clear
tempfile widedta
qui save `"`widedta'"'
qui reshape long inc, i(pid) j(year)
local o_long = _N
qui summ inc
local o_incsum = r(sum)

clear
parqit use using wide_income.parquet, name(wd)
parqit reshape long inc, i(pid) j(year)
parqit count
assert r(N) == `o_long'
parqit summarize inc
assert reldif(r(N) * r(mean), `o_incsum') < 1e-9
parqit reshape wide inc, i(pid grp) j(year)
parqit count
assert r(N) == 50
parqit close

* ----------------------------------------------------------------------------
di as txt _n "{hline 78}"
di as txt "section 8: SQL escape hatches"
di as txt "{hline 78}"

parqit sql "SELECT region, sector, avg(wage) AS aw, count(*) AS n FROM read_parquet('tour_workers.parquet') GROUP BY region, sector"
parqit count
assert r(N) > 0 & r(N) <= 20
parqit sort region sector
parqit head 6
parqit close

clear
parqit use using tour_workers.parquet, name(w)
parqit sort id year
parqit query "qualify row_number() over (partition by id order by year) = 1"
parqit count
assert r(N) == 200
parqit close

* ----------------------------------------------------------------------------
di as txt _n "{hline 78}"
di as txt "section 9: materialisers — collect, save (view|data), open _data"
di as txt "{hline 78}"

clear
parqit use using tour_workers.parquet, name(w)
parqit keep if year == 2021 & !missing(wage)
parqit keep id wage region
parqit collect, clear
local n21 = _N
assert c(k) == 3

* save the in-memory result while the view is still open: data option
gen byte from_memory = 1
parqit save tour_mem.parquet, replace data
* save the (still open) view: default target
parqit save tour_view.parquet, replace
parqit close _all

parqit describe tour_mem.parquet
assert r(n_cols) == 4
parqit describe tour_view.parquet
assert r(n_cols) == 3 & r(n_rows) == `n21'

* open _data: promote memory, aggregate out-of-core, bring it back
clear
set obs 60
gen g = mod(_n, 3)
gen x = _n
parqit open _data, name(mem)
parqit collapse (sum) sx = x, by(g)
parqit collect, clear
assert _N == 3
qui summ sx
assert r(sum) == 60 * 61 / 2
parqit close _all

* chunk(): rows per parquet row group (engine rounds to 2048-multiples)
clear
set obs 10000
gen long rid = _n
parqit save tour_chunked.parquet, replace chunk(2048)
parqit describe tour_chunked.parquet
assert r(n_row_groups) == 5 & r(n_rows) == 10000
capture erase tour_chunked.parquet

* statamissing mode
clear
parqit use using tour_workers.parquet, name(w)
parqit set statamissing on
qui parqit count if wage > 1
local n_stm = r(N)
parqit set statamissing off
qui parqit count if wage > 1
local n_sql2 = r(N)
assert `n_stm' == `n_sql2' + `o_miss'
parqit close _all

* ----------------------------------------------------------------------------
di as txt _n "{hline 78}"
di as txt "section 10: hostile files and loud errors"
di as txt "{hline 78}"

parqit describe messy.parquet
parqit use messy.parquet, clear
assert _N == 3
* reserved/space names renamed, values intact, originals kept in chars
assert _if[2] == 2
assert x_y[3] == 30
assert `"`: char _if[src_name]'"' == "if"
assert `"`: char x_y[src_name]'"' == "x y"
* uint32 beyond int32 arrives as values
assert u32[2] == 2147483648 & u32[3] == 4294967295
* decimal -> double with payload
assert reldif(money[1], 12.34) < 1e-12 & missing(money[3])
* duplicate columns both present
assert dup[1] == 100 & dup_1[1] == 7
* null-typed column is an all-missing byte
confirm byte variable allnull
assert missing(allnull[1])

* loud errors (a sample of the contract)
clear
parqit use using tour_workers.parquet, name(w)
capture parqit keep if frobnicate(wage)
assert _rc != 0
capture parqit gen wage = 1
assert _rc != 0
capture parqit merge m:1 year using firms.parquet
assert _rc != 0
capture parqit levelsof id, limit(10)
assert _rc != 0
capture parqit save tour_workers.parquet
assert _rc != 0
capture parqit use using no_such_file_anywhere.parquet, clear
assert _rc != 0
parqit close _all

di as txt _n "{hline 78}"
di as res "VERDICT(PARQIT_TOUR): PASS — every section verified against native Stata"
di as txt "{hline 78}"
